# Generated by Django 5.2.8 on 2025-11-17 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('google', 'Google (Gemini)'), ('other', 'Other')], max_length=50)),
                ('model_name', models.CharField(help_text='e.g., gpt-4, claude-3-opus', max_length=100)),
                ('api_key', models.CharField(help_text='Store encrypted in production', max_length=500)),
                ('is_active', models.BooleanField(default=False, help_text='Only one config can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('course', 'Course'), ('module', 'Module'), ('quiz', 'Quiz')], max_length=20)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the entity being generated', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_stage', models.CharField(choices=[('creating', 'Creating'), ('reviewing', 'Reviewing'), ('refining', 'Refining'), ('completed', 'Completed')], default='creating', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('message', models.TextField(blank=True, help_text='Current status message')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ai_generati_created_7e59e2_idx'), models.Index(fields=['status'], name='ai_generati_status_ec493d_idx'), models.Index(fields=['course'], name='ai_generati_course__4412b6_idx')],
            },
        ),
    ]
